#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// Include the HAL library for STM32F4 series, which provides 
#include "stm32f4xx_hal.h"

// Function prototype for post-initialization of Timer peripherals.
// actually an auto-generated by STM32CubeMX when
// advanced timer configuration is needed, for setting up PWM.
void HAL_TIM_MspPostInit(TIM_HandleTypeDef *htim);

// Error handler function again for connectivity related issues which uses internal clock 
void Error_Handler(void);


// Pin definitions for the SWD (Serial Wire Debug) interface on GPIOA.
// TMS and TCK are part of the debug interface, used to program and caliberate HX711 sensor readings from load cell 
// debug the STM32 microcontroller.
#define TMS_Pin GPIO_PIN_13          // TMS (Test Mode Select) pin on PA13
#define TMS_GPIO_Port GPIOA          // GPIO Port A for TMS
#define TCK_Pin GPIO_PIN_14          // TCK (Test Clock) pin on PA14
#define TCK_GPIO_Port GPIOA          // GPIO Port A for TCK

#ifdef __cplusplus
}
#endif

#endif

